
@host = localhost
@port = 8080


###

POST http://{{host}}:{{port}}/api/rpc HTTP/1.1
content-type: application/json

{
    "id": "1",
    "method": "create_task",
    "params": {
        "data": {
            "Title": "task from request http 1"
        }
    }
}

###
POST http://{{host}}:{{port}}/api/rpc HTTP/1.1
content-type: application/json

{
    "id": "1",
    "method": "list_tasks",
    "params": {
        "filters": [
            {
                "TaskID": "A1044F8D-1202-418C-9361-DE8B6E717152"
            }
        ],
        "list_options": {
            "start": 0,
            "limit": 50,
            "orderby": [
                {
                    "field": "CreateOn",
                    "is_desc": true
                }
            ]
        }
    }
}
###
POST http://{{host}}:{{port}}/api/rpc HTTP/1.1
content-type: application/json

{
    "id": "1",
    "method": "update_task",
    "params": {
        "id": "A1044F8D-1202-418C-9361-DE8B6E717152",
        "data": {
            "Title": "task from request http 1 updated",
            "Done": false
        }
    }
}

###
POST http://{{host}}:{{port}}/api/rpc HTTP/1.1
content-type: application/json

{
    "id": "1",
    "method": "delete_task",
    "params": {
        "id": "CF367697-B795-4C6F-815D-CF42EDED39B6"
    }
}


